### ISSUE TITLE
[BUG: Internal] Inconsistend behavior between normal text and bullet lists

### ISSUE THREAD

**Issue by nousernameavailableanymore** [tnichols217/obsidian-columns#45] opened 2023-01-09 01:34 UTC
# Describe the bug
When normal gets placed into "col" codeblock, new columns are created after each blank line.
However, when doing the same with bullet points, no additional columns get created and spacing is completely off.

## Steps To Reproduce
1. create codeblock:
````
```col
- line1
- line2
- line3

- line4
- line5
```
````

## Expected behavior
New column is created after blank line. Normal spacing is retained between items.

## Actual behavior
No new columns is created. Spacing is greatly increased.

## Screenshots
![image](https://user-images.githubusercontent.com/45376324/211229061-995ae567-d3bf-4db5-8db1-d739942aadbd.png)
![image](https://user-images.githubusercontent.com/45376324/211229096-3ed083dd-38dd-48b6-8c30-8faacafbe875.png)

## System Info
OS: Win10
Obsidian Version: 1.1.8
Plugin Version: 1.4.0

**Comment by tnichols217** [comment] 2023-01-09 02:18
This is intended, and part of the Obsidian markdown spec. If you put a blank line inside of a list it becomes a sparse most and the spacing will be greatly increased (you can try this outside of the col codeblock and see that the results are the same). If you want it to force to create two columns, you could use the col-md codeblock or add more newlines to specify a new element and not a sparse list

**Comment by nousernameavailableanymore** [comment] 2023-01-09 02:22
> 

What do you mean by "or add more newlines"? How would that look like?
By "use the col-md codeblock" you mean in combination with the wrapping "col" block, right?

**Comment by tnichols217** [comment] 2023-01-09 02:41
So for example, 
```md
- 1
- 2
- 3

- 4
```
(without the col codeblock)

Would create this:
![image](https://user-images.githubusercontent.com/62992267/211232915-40cd8b77-3ec6-4890-bc2e-2593575cd718.png)

When without that extra line it would create this:
![image](https://user-images.githubusercontent.com/62992267/211232944-527ea9f3-2674-491e-9c21-b4f52fb732d4.png)

Naturally, obsidian columns would have the same behavior.

Unfortunately though, adding additional newlines inbetween list elements does not separate them into separate lists, so obsidian columns does not separate them into different columns (even with more than one newline between elements).

As for the difference between lists and regular text in obsidian, when you have two newlines (a blank line) in the middle of a paragraph, obsidian will split the paragraph into two separate elements, which does not happen with lists because of the spare list feature from base obsidian.

And as for using the col-md codeblock, you could simply wrap the second column (or the first or both for that matter) with a col-md codeblock to force it to be on a different column like this:

`````md
````col
- 1
- 2
- 3

```col-md
- 4
```
````
`````

Producing: 
![image](https://user-images.githubusercontent.com/62992267/211233198-7acf8546-673f-465c-8332-7d6598a8cebd.png)

**Comment by tnichols217** [comment] 2023-02-03 11:46
Closing, as this is expected behavior

**Closed** 2023-02-03 11:46 UTC
Labels: bug, internal
