### ISSUE TITLE
Compatibility with live preview

### ISSUE THREAD

**Issue by ngirard** [tnichols217/obsidian-columns#3] opened 2022-04-28 08:16 UTC
It would be great if Obsidian-columns was compatible with live preview.

Meanwhile, I'd suggest mentioning the current state of affairs in the README.

**Comment by tnichols217** [comment] 2022-04-30 07:00
unfortunately this is my first plugin and i have 0 experience with live preview. I am willing to learn and try but i cant guarantee itll be fast. However, if you wanna add a pull request ill be all for it!

**Comment by DryIce1** [comment] 2022-05-01 05:53
Nice columns solution. But I work almost 100% in Live Preview. So I would also recommend stating in the readme that currently the plugin works in reading mode only.

**Comment by ngirard** [comment] 2022-05-01 06:10
Although I can't help with a PR, I could think of a list of extensions that significantly alter the DOM and are compatible with live preview, so that you take inspiration from them.
Would it help, @tnichols217 ?
If so, perhaps @DryIce1 could also think of relevant extensions as well ?

**Comment by tnichols217** [comment] 2022-05-01 06:21
Yea, in a way that would help!

**Comment by ngirard** [comment] 2022-05-01 08:04
Alright, so how about the [Buttons](https://github.com/shabegom/buttons) extension to begin with ? It seems small and the code doesn't look too cumbersome to my eyes.

**Comment by tnichols217** [comment] 2022-05-04 06:45
Ive been reading a lot of code an making the list mode compatible with live preview involves writing an extension for CodeMirror. Ive been reading the API on it but i probably will not be done with it anytime soon. When I begin coding ill open this issue in its own branch. I probably wouldnt get this done anytime soon im sorry (im still a highschool student) but as usual any PRs are welcome!

**Comment by ngirard** [comment] 2022-05-04 10:33
Well thanks for the heads up ! Take your time, no worries !

Cheers

**Comment by jaroet** [comment] 2022-05-19 08:05
Hello, 

I just found this plugin and it works nicely for me. Both in LivePreview and in Reading mode. The only difference is that in LivePreview the spacing is way too wide. I created a test page to illustrate the issue. 

LivePreview
![image](https://user-images.githubusercontent.com/28713432/169243307-95046030-f8d3-4960-963f-3e241be5a40e.png)

In Reading mode
![image](https://user-images.githubusercontent.com/28713432/169243393-0c34b1d6-f956-45df-b27b-5f8b46a22fdf.png)

I might be understating the issue but to me that looks like only changes to the CSS need to be made to have a nicely working plugin in LivePreview. 

On my original page I have a lot more links and columns so the extremely wide spacing will not work for me. 

I have a little knowledge of CSS in general but I never seem to be able to consistently change the CSS in Obsidian. I will post here if I might have found a way to change it. 

Again, I might be over-simplifying the issue. But I could the impressions from the previous comments that it was not working in Live Preview mode at all but it does for me. 

Regards,
JeRoen

**Comment by tnichols217** [comment] 2022-05-19 09:34
Alright I'll take a look in about 5 hours

**Comment by tnichols217** [comment] 2022-05-19 15:21
@jaroet I have absolutely no clue what could be causing it. The HTML and the CSS are exactly the same for the inner items and i dont see any inherited properties that could alter the line height. Have any ideas about what property it may be? Ill be looking around for a solution

**Comment by johans3** [comment] 2022-05-22 11:36
@jaroet
Hmm, did you try different themes? Your issue might be related to themes

**Comment by jaroet** [comment] 2022-05-23 17:40
Sorry for the long delay and thanks for looking into it...

I have a list in a column with bullets showing links to mainparts of my
vault. When I select the <ul> in developer mode I see the following CSS ...
[image: image.png]
1em is I think rather big and at least the 40px is quite a large
whitespace. Might this be the cause?

AS I am not sure how inheritance works and when certain CSS is applied or
not I am not sure and can't really test more.

The strange thing is that some CSS I can change in developmode or activate
or not by clicking a checkbox but those values that I think are the
cullprit I can not.

I hope this helps.

Regards,
JeRoen



Op zo 22 mei 2022 om 13:37 schreef johans3 ***@***.***>:

**Comment by jaroet** [comment] 2022-05-23 17:41
And also I use different themes indeed, but all have this issue including
the default theme.

Op ma 23 mei 2022 om 19:40 schreef jeroen ophetweb ***@***.***

**Comment by nousernameavailableanymore** [comment] 2022-05-29 03:44
I get the same as @jaroet .
The space between the lines is way too big in Live Preview.
I also use Live Preview exclusively (and tbh, I dont see a point why reading mode should still exist in the first place).

**Comment by nousernameavailableanymore** [comment] 2022-05-29 18:42
I found that if you add a snippet like the one below, it will actually fix the space between manual line breaks (if you press enter and create a new line).
However, this will cause the space between wrapping lines (lines that were to long to fit on the screen and wrapped around) to be extremely small.

I have no clue how to fix this.

CSS snippet:
```
.columnChild p{
	line-height: 0.8;
}
```

![image](https://user-images.githubusercontent.com/45376324/170886523-aee9d13d-8de4-42ec-bce0-f8f24bc99649.png)

**Comment by tnichols217** [comment] 2022-05-30 03:38
Line spacing was fixed in commit https://github.com/tnichols217/obsidian-columns/commit/cf2395824ea0b67287e35d6aad1b7bfa3edfd1e9 (v1.1.3) by adding a css snippet:
```css
.cm-preview-code-block .columnParent br {
    display: none;
}
```
to disable addition line breaks inside of live preview codeblocks

**Comment by tnichols217** [comment] 2022-05-30 03:39
Thanks for your help @nousernameavailableanymore @jaroet @johans3

**Comment by tnichols217** [comment] 2022-05-30 14:19
Ill take a look rn

**Comment by tnichols217** [comment] 2022-05-30 14:47
My bad, I fixed it with another CSS snippet: 

```css
.columnParent {
    white-space: normal
}
```
Pushed in commit https://github.com/tnichols217/obsidian-columns/commit/9935585920dc90396fc58599221a3a05d84d7249 
In release [`1.1.4`](https://github.com/tnichols217/obsidian-columns/releases/tag/1.1.4)

**Comment by TheChilliPL** [comment] 2022-11-23 09:25
Would it be possible to make markdown be syntax highlighted inside the \`\`\`col-md … \`\`\` codeblock?

**Comment by tnichols217** [comment] 2022-12-14 13:12
I believe that live preview is basically fully supported at this point with both codeblock and callout syntax, as list syntax is basically unused by users AFAIK. Closing issue.

**Comment by tnichols217** [comment] 2022-12-14 13:13
> Would it be possible to make markdown be syntax highlighted inside the ```col-md … ``` codeblock?

I think this was referenced in another issue, but I am looking into this

**Closed by tnichols217** 2022-12-14 13:12 UTC
Labels: enhancement, help wanted, future fix, Feature Request
