### ISSUE TITLE
Unable to display dataview queries 

### ISSUE THREAD

**Issue by johans3** [tnichols217/obsidian-columns#11] opened 2022-05-05 20:49 UTC
# dataview results get ignored
**Obsidian-columns** should support some very well known plugins like **Dataview plugin**. Current results get  ignored, if inside a **Obsidian-columns** code block

## Steps to reproduce:
Just place any kind of dataview query inside **Obsidian-columns**: (please add a valid path after "list from") 
`````css
````col
```dataview 
list from "templates/test" 
```
````
`````

## System Info
OS: Mac osx
Obsidian Version: 0.14.6
Plugin Version: 1.0.5

**Comment by tnichols217** [comment] 2022-05-05 23:59
Duplicate of #10 don't forget to update the plugin, it was patched in version 1.0.8 :)

**Closed** 2022-05-05 23:59 UTC

**Comment by tnichols217** [comment] 2022-05-06 00:01
As this plugin was created just over a week ago, sorry for all the bugs and problems popping up, but development is happening fast don't forget to update! If the problem persists in the latest release, don't resist to open a new issue. Hopefully all works well!
