### ISSUE TITLE
Obsidian Columns do not support Checkbox

### ISSUE THREAD

**Issue by Missionary2112** [tnichols217/obsidian-columns#22] opened 2022-06-12 01:43 UTC
# Describe the bug
Checkbox is not remembered and it's refreshed unchecked every time I visit back to the note.

## Steps To Reproduce
1. Create checkboxes in 3 columns.
2. In preview mode, check a few checkboxes
3. Go to another file and go back to the file
4. See error: the checkboxes were refreshed back to uncheck 

## Expected behavior
- The checkbox should be remembered once checked.

## Screenshots
- Edit mode: Red dot is invisible character.
![Screenshot - 2022-06-11 18 35 26 (Obsidian)](https://user-images.githubusercontent.com/98799613/173210580-5016dc4d-b864-4503-ae7c-1f4ccedff920.jpg)
- Preview mode: Example check 2 boxes
![Screenshot - 2022-06-11 18 34 49 (Obsidian)](https://user-images.githubusercontent.com/98799613/173210594-05b6ae78-7d8f-4cc2-a3e6-8c012077d8d9.jpg)
- When go to another file and return to the file, the checks are gone
![Screenshot - 2022-06-11 18 34 39 (Obsidian)](https://user-images.githubusercontent.com/98799613/173210604-2c355f58-637d-46db-b40c-b6ea697e0a40.jpg)

## System Info
OS: Monterey 12.4
Obsidian Version: v0.14.15
Plugin Version: 1.1.6

**Comment by tnichols217** [comment] 2022-06-12 01:46
Duplicate of #16

**Closed** 2022-06-12 01:56 UTC
Labels: duplicate
